xset m 10/4 1
xset r rate 200 50

xmodmap -e 'keycode 66 = Control_L'
xmodmap -e 'clear Lock'
xmodmap -e 'add Control = Control_L'
xidle -program "/usr/X11R6/bin/xlock" -timeout 300 &
xrdb /home/jack/.Xdefaults
xsetroot -solid black &
eval $(/usr/local/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
xterm -bg white -fg black -class wifi -e /bin/sh -l -c "sudo /home/jack/random/dotfiles/wifi.sh" &
i3

